- name: Adicionando /etc/apt/sources.list
  copy: src=sources.list dest=/etc/apt/sources.list

- name: Instalando pacotes
  apt: name={{item}} state=latest install_recommends=yes update_cache=yes
  with_items:
    - "{{ common_packages }}"

- name: Fazendo upgrade
  apt: upgrade=dist

- name: Update locale
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}

- name: Setando localtime
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

- name: Acertando timezone
  blockinfile:
    dest: /etc/timezone
    block: |
      {{timezone}}

- name: Configurando tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
   
- name: Setando vim
  action: shell update-alternatives --set editor /usr/bin/vim.basic

- name: Configurando vimrc
  lineinfile:
    dest=/etc/vim/vimrc
    regexp='"syntax on'
    line='syntax on'
    state=present
