# -*- mode: bash -*-
# vi: set ft=bash

- hosts: all
    sudo: True
    user: Vagrant
    task:
        - name: "Atualizando pacotes."
          shell: sudo apt-get update
        - name: "Instala o nginx."
          shell: sudo apt-get install nginx -y 

