- name: Adicionando repositorio NGINX.
  apt_repository: repo="deb http://nginx.org/packages/debian/ jessie nginx" state=present
- name: Adicionando chaves NGINX.
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present 
- name: apt-get update
  apt: update_cache=yes
- name: Configurando NGINX.
  apt: name=nginx state=latest install_recommends=yes
- name: Ativando NGINX.
  service: name=nginx state=started enabled=yes
- name: Copiando index.hmtl
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
