- name: Instalando pacotes
  apt: name={{item}} state=latest install_recommends=yes
  with_items:
    - "{{ xen_packages }}"

- name: Download do Xen.
  #Testar o unarchive com o https
  #unarchive: src=https://www.xenproject.org/downloads/xen-archives/xen-46-series/xen-461/329-xen-461/file.html dest=/usr/src/ copy=no
  get_url: url=http://www.xenproject.org/downloads/xen-archives/xen-46-series/xen-461/329-xen-461/file.html dest=/usr/src/xen-4.6.1.tar.gz validate_certs=no

- name: Descompactando Xen.
  command: tar zxf /usr/src/xen-4.6.1.tar.gz -C /usr/src

- name: Clean Xen.
  make: 
    chdir: /usr/src/xen-4.6.1
    target: clean
    params:
      NUM_THREADS: 2

- name: Preparando
  shell: echo "PYTHON_PREFIX_ARG=--install-layout=deb" > /usr/src/xen-4.6.1/.config

- name: Configure Xen.
  command: ./configure --libdir=/usr/lib --enable-systemd chdir=/usr/src/xen-4.6.1

- name: Make dist
  make:
    chdir: /usr/src/xen-4.6.1
    target: dist
    params:
      NUM_THREADS: 2

- name: Make install
  make:
    chdir: /usr/src/xen-4.6.1
    target: install
    params:
      NUM_THREADS: 2

- command: ldconfig chdir=/usr/src/xen-4.6.1

- name: Ativando Xen.
  command: systemctl enable xenstored.service
- command: systemctl enable xenconsoled.service
- command: systemctl enable xen-init-dom0.service
- command: systemctl enable xen-qemu-dom0-disk-backend.service
#- command: systemctl enable xendomains.service
- copy: src=08_xen dest=/etc/grub.d/

- name: Reiniciando Servidores.
  shell: sleep 2 && reboot -n
  async: 1
  poll: 0
  ignore_errors: true

# Falta fazer o /etc/grub.d/08_xen
