- hosts: all
  sudo: True
  user: vagrant
  vars: 
    mysql_root_password: root
    mysql_wp_user: wordpress
    mysql_wp_password: wordpress
    wordpress_db_name: wordpress

  tasks:
    # INSTALACAO DE PACOTES
    #- name: "Atualizando pacotes e instalando NGINX."
    #  apt: name=nginx state=latest update_cache=yes install_recommends=yes
    #- name: "Instala PHP-FPM."
    #  apt: name=php5-fpm state=latest install_recommends=yes
    #- name: "Instala PHP-MYSQL."
    #  apt: name=php5-mysql state=latest install_recommends=yes
    #- name: "Instala MYSQL."
    #  apt: name=mysql-server state=latest install_recommends=yes
    #- name: "Instala PYTHON-MYSQLDB."
    #  apt: name=python-mysqldb state=latest install_recommends=yes
    #- name: "Instala NMAP."
    #  apt: name=nmap state=latest install_recommends=yes
    - name: "ATUALIZANDO PACOTES E INSTALANDO PACOTES NECESSARIOS."
      apt: name={{item}} state=latest update_cache=yes install_recommends=yes
      with_items:
        - nginx
        #- php5-fpm
        #- php5-mysql
        #- mysql-server
        #- python-mysqldb
        #- nmap
        #- vim
        #- screen
        
    

    # COPIA DE ARQUIVOS 
    #- name: "Criando diretorio /opt/wordpress."
    #  file: dest=/opt/wordpress state=directory mode=0755 owner=www-data
    #- name: "Copia arquivo de configuracao nginx."
    #  copy: src=blog.nginx dest=/etc/nginx/sites-available/blog
    #- name: "Copia arquivo index.php."
    #  copy: src=index.php dest=/opt/wordpress/ mode=0755 owner=www-data group=www-data
    #- name: "Ativa o site."
    #  file: src=/etc/nginx/sites-available/blog dest=/etc/nginx/sites-enabled/blog state=link
    #- name: "Apaga default page."
    #  file: path=/etc/nginx/sites-enabled/default state=absent
  # 
  #  # DOWNLOAD WORDPRESS 
  #  - name: "Download do WORDPRESS."
  #    get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/latest.tar.gz
  #  - name: "Descompactando WORDPRESS."
  #    unarchive:  src=/tmp/latest.tar.gz  dest=/opt copy=no
  #  - name: "Corrige  permissoes."
  #    file: path=/opt/wordpress recurse=yes owner=www-data group=www-data
  #  
  #  # SERVICOS
  #  - name: "Reinicia o NGINX."
  #    service: name=nginx state=restarted
  #  - name: "Iniciando MYSQL."
  #    service: name=mysql state=restarted enabled=true
#
##    # MYSQL
##    - name: "Criando .MY.CNF."
##      template: src=my.cnf.j2 dest=~/.my.cnf mode=0600
##    - name: "Criando senhas MYSQL."
##      mysql_user: name=root 
##                  password="{{ mysql_root_password }}"
##                  check_implicit_admin=yes
##                  priv="*.*:ALL,GRANT"
##                  state=present
##                  host="{{ item }}"
##      with_items:
##        - "{{ ansible_hostname }}"
##        - 127.0.0.1
##        - *1
##        - localhost
##
#    #- name: "Criando WORDPRESS DATABASE."
#    #  mysql_db: name=wordpress login_user=root login_password="{{ mysql_root_password }}" state=present
#    #- name: "Criando USUARIO WORDPRESS."
#    #  mysql_user: name="{{ mysql_wp_user }}" password="{{ mysql_wp_password }}" priv="{{ wordpress_db_name }}".*:ALL check_implicit_admin=yes login_user=root
#    #              login_password="{{ mysql_root_password }}" host="{{ item }}" state=present
#    #  with_items:
#    #    - "{{ ansible_hostname }}"
#    #    - 127.0.0.1
#    #    - *1
#    #    - localhost
