- hosts: all
  sudo: True
  user: vagrant

  tasks: 
  # ESTRUTURA
    # diretorios
    - name: "SISTEMA OPERACIONAL: CRIANDO DIRETORIOS"
      file: dest={{item}} state=directory mode=0755 
      with_items:
        - /var/log/gsim/info
        - /mnt/cdrom
        - /home/httpd
        - /home/espelho2
        - /u/erpsim/pgsql
        - /u/erpsim/httpd/html/gsim
        - /usr/local/gsim
        - /etc/php4/apache2
        - /usr/kerberos
        - /lib/kerberos
    # adicionando usuario
    - name: "SISTEMA OPERACIONAL: ADICIONANDO USUARIO GSS."
      user: name=gss shell=/bin/bash 
    - name: "SISTEMA OPERACIONAL: ADICIONANDO GRUPO SIM."
      group: name=sim gid=51 state=present
    - name: "SISTEMA OPERACIONAL: ADICIONANDO USUARIOS DOS SISTEMAS."
      user: name={{ item.name }} shell=/bin/bash group=sim home={{ item.home }} move_home=yes state=present
      with_items:
        - { name: 'contab2', home: '/u/contab2' }
  # PACOTES
    - file: path=/etc/apt/sources.list state=absent
    - name: "SISTEMA OPERACIONAL: ADICIONANDO REPOSITORIO"
      apt_repository: repo='{{item}}' state=present
      with_items:
        - deb [arch=amd64,i386] http://http.debian.net/debian jessie main contrib non-free
        - deb [arch=amd64,i386] http://http.debian.net/debian jessie-updates main contrib non-free
        - deb [arch=amd64,i386] http://security.debian.org/ jessie/updates main contrib non-free
        - deb http://nginx.org/packages/debian/ jessie nginx
        - deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
    - name: "SISTEMA OPERACIONAL: ADICIONANDO CHAVES"
      apt_key: url={{item}} state=present
      with_items:
        - http://nginx.org/keys/nginx_signing.key
        - https://www.postgresql.org/media/keys/ACCC4CF8.asc
    - name: "SISTEMA OPERACIONAL: APT-GET UPDATE"
      apt: update_cache=yes
    - name: "SISTEMA OPERACIONAL: INSTALANDO PACOTES"
      apt: name={{item}} state=latest install_recommends=yes 
      with_items:
        - apt-file
        - aptitude
        - screen
        - iptraf
        - nmon
        - htop
        - tcpdump
        - splitvt
        - iftop
        - bzip2
        - bc
        - bcc
        - bind9utils
        - binutils
        - bison
        - bridge-utils
        - build-essential
        - ca-certificates
        - dialog
        - dnsutils
        - dpkg-dev
        - expect
        - file
        - fping
        - flex
        - fuse
        - genisoimage
        - geoip-database
        - hdparm
        - iotop
        - iproute
        - iptraf
        - iperf
        - lsof
        - links
        - lynx
        - links2
        - less
        - lsof
        - libfl-dev
        - libdbd-pg-perl
        - libossp-uuid16
        - libxtst6
        - libregina3
        - logtail
        - lsb-release
        - less
        - mtools
        - minicom
        - nmap
        - ntfs-3g
        - psmisc
        - ptop
        - pv
        - python-dev
        - python-pam
        - python-beautifulsoup
        - python-pysqlite2
        - python-setuptools
        - python-twisted
        - python-egenix-mxdatetime
        - python-egenix-mxtools
        - python-fpconst
        - python-psycopg2
        - python-soappy
        - rcconf
        - rsync
        - sharutils
        - sqlite3
        - subversion
        - sudo
        - sysstat
        - splitvt
        - sshfs
        - wodim
        - wget
        - unzip 
        - usbmount
        - vim
        - slurm
        - dstat
        - openssh-server
        - postfix
        - openvpn
        - tomcat7-user
        - tomcat7-common
        - tomcat7-admin
        - tomcat7
        - libasound2 
        - libatk1.0-0 
        - libgdk-pixbuf2.0-0 
        - libgl1-mesa-glx 
        - libgtk2.0-0 
        - libpangocairo-1.0-0 
        - libxxf86vm1
        - bluez-cups
        - cups-driver-gutenprint
        - cups-filters
        - cups-pdf
        - escputil
        - foomatic-db
        - foomatic-db-engine
        - foomatic-db-gutenprint
        #- foomatic-filters
        - hplip
        - hplip-data
        - hpijs-ppds
        - system-config-printer-udev
        - c2050
        - ijsgutenprint
        - printer-driver-all-enforce
        - samba
        - samba-common-bin
        - samba-common
        - smbclient
        - smbc
        - fusesmb
        - linux-headers-amd64
        - aspell
        - aspell-en
        - aspell-pt-br
        - autoconf
        - automake
        - autotools-dev
        - chrpath
        - debhelper
        - dictionaries-common
        - diffstat
        - firebird-dev
        - firebird2.5-common
        - firebird2.5-common-doc
        - freetds-common
        - freetds-dev
        - gettext
        - hardening-wrapper
        - html2text
        - intltool-debian
        - libaio1
        - libapr1-dev
        - libaprutil1-dev
        - libaspell-dev
        - libaspell15
        - libbz2-dev
        - libc-client2007e
        - libc-client2007e-dev
        - libcroco3
        - libct4
        - libcurl4-openssl-dev
        - libdb-dev
        - libdb5.3-dev
        - libdbd-mysql-perl
        - libdbi-perl
        - libelf1
        - libenchant-dev
        - libenchant1c2a
        - libevent-2.0-5
        - libevent-core-2.0-5
        - libevent-dev
        - libevent-extra-2.0-5
        - libevent-openssl-2.0-5
        - libevent-pthreads-2.0-5
        - libfbclient2
        - libgettextpo0
        - libglib2.0-bin
        - libglib2.0-data
        - libglib2.0-dev
        - libgmp-dev
        - libgmp3-dev
        - libgmpxx4ldbl
        - libhunspell-1.3-0
        - libib-util
        - libicu-dev
        - libicu52
        - libjpeg62-turbo-dev
        - libltdl-dev
        - libmagic-dev
        - libmcrypt-dev
        - libmcrypt4
        - libmhash-dev
        - libmhash2
        - libmysqlclient-dev
        - libmysqlclient18
        - libnet-daemon-perl
        - libodbc1
        - libonig-dev
        - libonig2
        - libpam0g-dev
        - libpcre3-dev
        - libpcrecpp0
        - libpspell-dev
        - libpthread-stubs0-dev
        - libqdbm-dev
        - libqdbm14
        - librecode-dev
        - librecode0
        - libsqlite3-dev
        - libsybdb5
        - libtidy-0.99-0
        - libtidy-dev
        - libtool
        - libunistring0
        - libx11-dev
        - libxau-dev
        - libxcb1-dev
        - libxdmcp-dev
        - libxml2-dev
        - libxmltok1
        - libxmltok1-dev
        - libxpm-dev
        - libxslt1-dev
        - locales-all
        - mlock
        - odbcinst1debian2
        - po-debconf
        - psmisc
        - quilt
        - re2c
        - unixodbc
        - unixodbc-dev
        - uuid-dev
        - uuid
        - x11-common
        - x11proto-core-dev
        - x11proto-input-dev
        - x11proto-kb-dev
        - xorg-sgml-doctools
        - xtrans-dev
        - libfreetype6-dev
        - libpng12-dev
        - libkrb5-dev
        - libxft-dev
        - libpangoxft-1.0-0
        - libpq-dev
        - libpq5
        - libdbd-pg-perl
        - gawk
        - liblua5.1-0-dev
        - libreadline-dev
        - libreadline6-dev
        - libtinfo-dev
        - postgresql-9.4
        - postgresql-client-9.4
        - postgresql-contrib-9.4
        - postgresql-9.4-plsh
        - postgresql-9.4-prefix
        - procmail
        - libc6
        - libc6-dev
        - libc-dev-bin
        - libtiff5-dev
        - nginx
    - name: "SISTEMA OPERACIONAL: COPIANDO JAVA."
      copy: src=pacotes/oracle-java7-jre_7u80_amd64.deb dest=/tmp/oracle-java7-jre_7u80_amd64.deb force=yes
    - name: "SISTEMA OPERACIONAL: INSTALANDO JAVA."
      apt: deb=/tmp/oracle-java7-jre_7u80_amd64.deb 
    - name: "SISTEMA OPERACIONAL: CONFIGURANDO JAVA 1/3."
      shell: update-alternatives --install /usr/bin/java java /usr/lib/jvm/jre-7-oracle-x64/bin/java 1065
    - name: "SISTEMA OPERACIONAL: CONFIGURANDO JAVA 2/3."
      shell: update-alternatives --set java /usr/lib/jvm/jre-7-oracle-x64/bin/java
    - name: "SISTEMA OPERACIONAL: CONFIGURANDO JAVA 3/3."
      copy: src=arquivos/Arial.ttf dest=/usr/lib/jvm/jre-7-oracle-x64/lib/fonts force=yes

    # gerando links para php4
    - name: "SISTEMA OPERACIONAL: GERANDO LINKS"
      file: src={{item.origem}} dest={{item.destino}} state=link
      with_items:
        - { origem: '/u/erpsim/httpd/html', destino: '/home/httpd/html' }
        - { origem: '/usr/lib/x86_64-linux-gnu/libjpeg.so', destino: '/usr/lib/libjpeg.so'}
        - { origem: '/usr/lib/x86_64-linux-gnu/libXpm.so', destino: '/usr/lib/libXpm.so' }
        - { origem: '/usr/lib/x86_64-linux-gnu/libtiff.so', destino: '/usr/lib/libtiff.so' }
        - { origem: '/usr/lib/x86_64-linux-gnu/libpng.so', destino: '/usr/lib/libpng.so' }
        - { origem: '/usr/lib/x86_64-linux-gnu', destino: '/usr/kerberos/lib' }
        - { origem: '/usr/include/freetype2/freetype.h', destino: '/usr/lib/freetype.h' }
        - { origem: '/usr/include', destino: '/opt/include' }
        #- { origem: '/usr/lib/x86_64-linux-gnu', destino: '/usr/lib/' }
        #- { origem: '/lib/terminfo', destino: '/usr/share/terminfo' }
    # arquivos de configuracao
    - name: "SISTEMA OPERACIONAL: COPIANDO ARQUIVOS DE CONFIGURACAO."
      copy: src={{item.origem}} dest={{item.destino}} force=yes
      with_items:
        - { origem: 'arquivos/bash.bashrc', destino: '/etc/bash.bashrc' }
        - { origem: 'arquivos/sshd_config', destino: '/etc/ssh/sshd_config' }
    - name: "SISTEMA OPERACIONAL: ACERTANDO O VIM."
      shell: update-alternatives --set editor /usr/bin/vim.basic
    - name: "SISTEMA OPERACIONAL: CONFIGURANDO SSH."
      shell: ssh-keygen -f /etc/ssh/ssh_host_key -N '' -t rsa1 2>/dev/null

    # TOMCAT
    - name: "TOMCAT7: STOP."
      service: name=tomcat7 state=stopped
    - name: "TOMCAT7: MOVENDO ESTRUTURA."
      command: creates="/u/erpsim/webapps" mv /var/lib/tomcat7/webapps /u/erpsim/webapps
    - name: "TOMCAT7: CRIANDO LINK."
      file: src=/u/erpsim/webapps dest=/var/lib/tomcat7/webapps state=link
    - file: dest=/u/erpsim/webapps/ROOT/gti state=directory mode=0755
    - name: "TOMCAT7: COPIANDO ARQUIVOS DE CONFIGURACAO."
      copy: src={{item.origem}} dest={{item.destino}} force=yes 
      with_items:
        - { origem: 'arquivos/server.xml', destino: '/etc/tomcat7/server.xml' }
        - { origem: 'arquivos/tomcat-users.xml', destino: '/etc/tomcat7/tomcat-users.xml' }
        - { origem: 'arquivos/etc-default-tomcat7', destino: '/etc/default/tomcat7' }
        - { origem: 'arquivos/application.css', destino: '/u/erpsim/webapps/ROOT/gti' }

    # NGINX
    - name: "NGINX: STOP."
      service: name=nginx state=stopped
    - name: "NGINX: COPIANDO ARQUIVOS DE CONFIGURACAO."
      copy: src={{item.origem}} dest={{item.destino}} force=yes
      with_items:
        - { origem: 'arquivos/default.conf', destino: '/etc/nginx/conf.d/default.conf' }
        - { origem: 'arquivos/fastcgi_params', destino: '/etc/nginx/fastcgi_params' }
        - { origem: 'arquivos/nginx.conf', destino: '/etc/nginx/nginx.conf' }

    # POSTGRESQL
    - name: "POSTGRESQL: STOP."
      service: name=postgresql state=stopped
    - name: "POSTGRESQL: COPIANDO ARQUIVOS DE CONFIGURACAO."
      copy: src={{item.origem}} dest={{item.destino}} force=yes
      with_items:
        - { origem: 'arquivos/pg_hba.conf', destino: '/etc/postgresql/9.4/main/pg_hba.conf' }
        - { origem: 'arquivos/postgresql.conf', destino: '/etc/postgresql/9.4/main/postgresql.conf' }
        - { origem: 'arquivos/dump_restore.py', destino: '/usr/bin/dump_restore.py', mode=0755 }
    - name: "POSTGRESQL: MOVENDO ESTRUTURAL."
      command: creates="/u/erpsim/pgsql/9.4" mv /var/lib/postgresql/9.4 /u/erpsim/pgsql/9.4
    - name: "POSTGRESQL: CRIANDO LINK."
      file: src=/u/erpsim/pgsql/9.4 dest=/var/lib/postgresql/9.4 state=link
    
