#   -*- mode:   ruby    -*-
#   vi: set ft=ruby :
VAGRANTFILE_API_VERSION =   "2"
Vagrant.configure(VAGRANTFILE_API_VERSION)  do  |config|
        config.vm.define    "sl8"    do  |sl8|
           sl8.vm.box   =   "debian/jessie64"
           sl8.vm.network   :private_network,   ip: "10.0.117.2"
           sl8.vm.provision "ansible" do | ansible | 
               ansible.playbook = "sl8.yml"
               #ansible.verbose = "vvv"
           end
        end

        config.vm.provider  "virtualbox"    do  |v|
                v.customize ["modifyvm",    :id,    "--memory", "1024"]
        end
end
