- name: Preparando sources.list
  copy: src=sources.list dest=/etc/apt/sources.list 
- name: apt-get update
  apt: update_cache=yes
- name: apt-get upgrade
  apt: upgrade=dist
- name: Instalando pacotes.
  apt: name={{item}} state=latest install_recommends=yes
  with_items:
    - "{{ common_packages }}"
- name: Configurando locale.
  action: shell locale-gen pt_BR.UTF-8
- name: Atualizando locale.
  action: shell locale-gen
- name: Configurando vim.
  action: shell update-alternatives --set editor /usr/bin/vim.basic
- name: Finalizando vim.
  lineinfile:
    dest=/etc/vim/vimrc
    regexp='"syntax on'
    line='syntax on'
    state=present
