- name: Adicionando chaves
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present validate_certs=no

- name: Adicionando repositorio.
  apt_repository: repo='deb http://nginx.org/packages/debian/ jessie nginx' state=present

- name: Instalando pacotes.
  apt: name=nginx state=latest install_recommends=yes update_cache=yes

- name: Copiando arquivo.
  copy: src=files/index.php dest=/usr/share/nginx/html

