- name: "Instalando pacotes"
  apt: name={{item}} state=latest install_recommends=yes
  with_items:
    - "{{ linux_packages }}"

- name: "Download do Kernel."
  get_url: url=https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.5.5.tar.xz dest=/usr/src/ validate_certs=no checksum=md5:9eac87725b45946890d2782429511e31

- name: "Descompactando Kernel."
  command: tar -Jxf /usr/src/linux-4.5.5.tar.xz -C /usr/src/

- name: "Copiando .config"
  copy: src=/boot/config-3.16.0-4-amd64 dest=/usr/src/linux-4.5.5/.config

- name: "Adaptando Kernel."
  make: 
    chdir: /usr/src/linux-4.5.5 
    target: olddefconfig 
    params: 
      NUM_THREADS: 2

- name: "Make xenconfig."
  make: 
    chdir: /usr/src/linux-4.5.5 
    target: xenconfig
    params: 
      NUM_THREADS: 2

- name: "Make all."
  make: 
    chdir: /usr/src/linux-4.5.5 
    target: all
    params: 
      NUM_THREADS: 2

- name: "Make modules_install."
  make: 
    chdir: /usr/src/linux-4.5.5 
    target: modules_install
    params: 
      NUM_THREADS: 2

- name: "Copiando o Linux"
  command: cp {{ item.origem}} {{ item.destino }} 
  with_items:
    - { origem: '/usr/src/linux-4.5.5/System.map', destino: '/boot/System.map-4.5.5' }
    - { origem: '/usr/src/linux-4.5.5/.config', destino: '/boot/config-4.5.5' }
    - { origem: '/usr/src/linux-4.5.5/arch/x86_64/boot/bzImage', destino: '/boot/vmlinuz-4.5.5' }

- name: "mkinitramfs"
  command: mkinitramfs -o /boot/initrd.img-4.5.5 4.5.5 chdir=/lib/modules

- name: "Upgrade-grub"
  command: update-grub2

- name: "Reiniciando o servidor."
  shell: sleep 2 && reboot -n 
  async: 1
  poll: 0
  ignore_errors: true

- name: "Esperando o servidor voltar."
#  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30

