- name: "Instalando pacotes"
  apt: name={{item}} state=latest install_recommends=yes
  with_items:
    - libncurses5-dev
    - build-essential
    - libncurses-dev 
    - ncurses-dev
    - gcc
    - bison
    - make 
    - automake
- name: "Download do Kernel."
  unarchive: src=https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.5.4.tar.xz dest=/usr/src/ copy=no
- name: "Copiando .config"
  copy: src=/boot/config-3.16.0-4-amd64 dest=/usr/src/linux-4.5.4/.config
- name: "Compilando"
  command: make xenconfig chdir=/usr/src/linux-4.5.4
- name: "Compilando"
  command: make -j2 all chdir=/usr/src/linux-4.5.4
- name: "Instalando Modulos"
  command: make -j2 modules_install chdir=/usr/src/linux-4.5.4 
- name: "Finalizando o Linux"
  # Nao consegui identificar ate agora o erro do modulo copy
  #copy: src={{ item.origem }} dest={{ item.destino }} force=yes
  command: cp {{ item.origem}} {{ item.destino }} 
  with_items:
    - { origem: '/usr/src/linux-4.5.4/System.map', destino: '/boot/System.map-4.5.4' }
    - { origem: '/usr/src/linux-4.5.4/.config', destino: '/boot/config-4.5.4' }
    - { origem: '/usr/src/linux-4.5.4/arch/x86_64/boot/bzImage', destino: '/boot/vmlinuz-4.5.4' }
- name: "mkinitramfs"
  command: mkinitramfs -o /boot/initrd.img-4.5.4 4.5.4 chdir=/lib/modules
- name: "Upgrade-grub"
  command: update-grub2
